# Site
repository: github.com/Ascaris-Equi
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jiahao Ma
# title: Biological Engineering
address: Harbin Institute of Technology, Wehai, 264209, China
email: Hourse_Ten@outlook.com #(optional)
phone: (+86)15689117509 #(optional)
website: https://github.com/Ascaris-Equi #(optional)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
# github_username:  elenathFGS
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: ElenathFGS
# flickr_username: jekyll
# instagram_username: fgs218ok
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: My CV
   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
   url: paper/CV-MAJIAHAO.pdf

# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Images/mmexport1592582783149.jpg # Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
 Hi, my name is Jiahao Ma, and I’m getting my B.E. from Harbin Institute of Technology. I’m previously studing and doing research at HIT Analytical Science and Technology Center,
 unter the supervision of Prof. Guangfeng Kan. In a few months, I will go to Yantai Coastal Zone Research Institute of Chinese Academy of Sciences for joint training. 
 Currently I’m conducting the research subject of Informed neural network architecture under the guidance of Dr. Robin  Singh.
  
  My major interest lies in:
  * Application of neural network in quantitative biology
  * Graph database of biological signal transduction network
  * Adaptation mechanism of marine microorganisms to extreme and stress.


  

#You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#  - Lists
#  - Tables
#  - <a href="google.com">Links</a>
#  - Images

# Projects Section
projects_title: Current Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Experience & Awards #(Use this to override about experience section title)

# Education Section
education_title: Publications #(Use this to override about education section title)

# More Section
more_title: A little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  In my spare time, I am a fan of Basketball & Mixed martial arts. In addition, I also like to write pranks or strange small works, some of which can be seen in my GitHub repositories.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
